# Generated by Django 4.2.4 on 2023-08-31 14:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('video', models.FileField(blank=True, null=True, upload_to='about_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', tinymce.models.HTMLField()),
                ('answer', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LW.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('heading', models.CharField(blank=True, max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('image', models.ImageField(default=None, null=True, upload_to='topic_images/')),
                ('points', tinymce.models.HTMLField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LW.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LW.subject')),
            ],
        ),
    ]
