# Generated by Django 4.2.4 on 2023-08-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LW', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='video',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
    ]
