# Generated by Django 4.2.4 on 2023-08-31 15:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('LW', '0002_remove_about_video_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='right_text',
            field=tinymce.models.HTMLField(default=2),
            preserve_default=False,
        ),
    ]
